// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6M6rayZhZfX1djnzXGlQ3I7Muf7sDtig',
    appId: '1:703500566858:web:2895d9f1613e2afe2901b3',
    messagingSenderId: '703500566858',
    projectId: 'catelyn-pet-shop',
    authDomain: 'catelyn-pet-shop.firebaseapp.com',
    storageBucket: 'catelyn-pet-shop.appspot.com',
    measurementId: 'G-KK7LFVYFYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALP4riHY2Ugl91VnhQvgu2thKy3fSfcSc',
    appId: '1:703500566858:android:b1177ff18d5d252b2901b3',
    messagingSenderId: '703500566858',
    projectId: 'catelyn-pet-shop',
    storageBucket: 'catelyn-pet-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlhEDMcxELUm2k9edqIRnSJdOK3P4FKiw',
    appId: '1:703500566858:ios:4a400ca79cfc07ff2901b3',
    messagingSenderId: '703500566858',
    projectId: 'catelyn-pet-shop',
    storageBucket: 'catelyn-pet-shop.appspot.com',
    iosBundleId: 'info.shovon.catelynePetFlutter',
  );
}
